### ISSUE TITLE
Manual trigger to set defaults

### ISSUE THREAD

**Issue by andreapalisca** [atbore-phx/sbam#25]
Issue: if HA is not running (crashed or power outage) at the end of the favourable time window and the inverter was charging the battery, the inverter keeps charging until the start of the next favourable window, which can be a day later. I'm running HAOS and I haven't found a way to manually set defaults to stop the inverter from charging the battery. I'd like to be able to write an automation that after a HA restart, it sets Fronius to defaults to avoid it charging outside of the favourable window. Thank you!

**Comment by atbore-phx** [comment]
Hi @andreapalisca,

I suggest to activate those two options in the add-on configuration panel to enable an auto restart when HA will be back online.
![Screenshot_2024-10-03-11-50-16-77_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/user-attachments/assets/6dcc8e14-7f21-49ce-a00b-e4d8ab7ad23a)

When you are outside the working windows and you want to create your automation you can execute sham via it's standalone binary available under the release section of this repository.
The command option is `sbam configure` you have a flag for defaults (-d)

**Comment by andreapalisca** [comment]
Thank you for your help @atbore-phx. It would be great to have these commands available somehow also in HACS Add-on installation mode.
