### ISSUE TITLE
Auto Pw_Consumption possible??

### ISSUE THREAD

**Issue by Fab5962** [atbore-phx/sbam#27]
Hi @atbore-phx !

Thanks a lot for this great job, since I dream of this functionality in HA!
I wonder if it could be possible to implement a function which calculate the average of a daily electrical consumption (in my case it's really different between the winter and the summer, between a cloudy and sunny day (windows are oriented sud) -> I heat my house with electrical)?
And do you think it could be possible to force the battery charge to 100% in some cases? (I have an electrical subscription called Tempo in France 44 days a year, very expensive and starts at 6am?

Thank You!

**Comment by atbore-phx** [comment]
hi @Fab5962,
