### ISSUE TITLE
Charge don t start , and few ideas...

### ISSUE THREAD

**Issue by ougueur** [atbore-phx/sbam#50]
Hello, first of all thank you for this excellent idea 🙂👍.
My battery charge does not start yet the parameters are good .. in my opinion ...

A minimum charging power has been imposed for the battery (before knowing your add-on, I forced my gen24+ inverter to charge the byd battery by putting the battery management parameter in manual and minimum charge 100%.)
But despite this the battery only charges at about 500/700w and my battery was not full when I woke up at the end of the economic hours ...
With the solar surplus it can charge up to 4000w ... I have no more surplus for the moment ....

The economic hours are from 10 p.m. to midnight and midnight to 6 a.m. at my place, should I write 10 p.m. in start hr and 6 a.m. in end hr?

 Can add a parameter for variable rate subscriptions depending on the day, (EDF tempo in France)

Can we make the pw consumption parameter variable depending on the outside temperature (full electric heating by heat pump) my daily consumption depends mainly on the outside temperature.

What is the pw bat reserve parameter used for when the inverter does not know the remaining capacity but only the charge percentage..?

Thank you in advance for the time you will spend reading me 😁,
Sorry for the translation my English is not very good..

If attached log sbam

s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
{"level":"debug","ts":"2024-12-17T21:54:44+01:00","msg":"Debug Logs activated: true"}
{"level":"info","ts":"2024-12-17T21:54:44+01:00","msg":"Setting Fronius Storage Defaults start..."}
{"level":"debug","ts":"2024-12-17T21:54:44+01:00","msg":"Reading register: 40351 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-17T21:54:44+01:00","msg":"Reading register: 40361 ; value: 1; default:"}
{"level":"debug","ts":"2024-12-17T21:54:44+01:00","msg":"Reading register: 40349 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-17T21:54:44+01:00","msg":"Reading register: 40356 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-17T21:54:44+01:00","msg":"Reading register: 40357 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-17T21:54:44+01:00","msg":"Writing register: 40361 ; value: 1"}
{"level":"debug","ts":"2024-12-17T21:54:44+01:00","msg":"Writing register: 40349 ; value: 0"}
{"level":"debug","ts":"2024-12-17T21:54:44+01:00","msg":"Writing register: 40356 ; value: 10000"}
{"level":"debug","ts":"2024-12-17T21:54:44+01:00","msg":"Writing register: 40357 ; value: 10000"}
{"level":"debug","ts":"2024-12-17T21:54:44+01:00","msg":"Writing register: 40351 ; value: 0"}
{"level":"info","ts":"2024-12-17T21:54:44+01:00","msg":"Setting Fronius Modbus Defaults done."}
{"level":"debug","ts":"2024-12-17T21:54:44+01:00","msg":"Debug Logs activated: true"}
Running, press ctrl+c to exit...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
{"level":"debug","ts":"2024-12-17T22:28:07+01:00","msg":"Debug Logs activated: true"}
{"level":"info","ts":"2024-12-17T22:28:07+01:00","msg":"Setting Fronius Storage Defaults start..."}
{"level":"debug","ts":"2024-12-17T22:28:07+01:00","msg":"Reading register: 40361 ; value: 1; default:"}
{"level":"debug","ts":"2024-12-17T22:28:07+01:00","msg":"Reading register: 40349 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-17T22:28:07+01:00","msg":"Reading register: 40356 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-17T22:28:07+01:00","msg":"Reading register: 40357 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-17T22:28:07+01:00","msg":"Reading register: 40351 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-17T22:28:07+01:00","msg":"Writing register: 40349 ; value: 0"}
{"level":"debug","ts":"2024-12-17T22:28:07+01:00","msg":"Writing register: 40356 ; value: 10000"}
{"level":"debug","ts":"2024-12-17T22:28:07+01:00","msg":"Writing register: 40357 ; value: 10000"}
{"level":"debug","ts":"2024-12-17T22:28:07+01:00","msg":"Writing register: 40351 ; value: 0"}
{"level":"debug","ts":"2024-12-17T22:28:07+01:00","msg":"Writing register: 40361 ; value: 1"}
{"level":"info","ts":"2024-12-17T22:28:07+01:00","msg":"Setting Fronius Modbus Defaults done."}
{"level":"debug","ts":"2024-12-17T22:28:07+01:00","msg":"Debug Logs activated: true"}
Running, press ctrl+c to exit...
{"level":"error","ts":"2024-12-18T00:00:01+01:00","msg":"Error getting forecast for https://api.solcast.com.au/rooftop_sites/3155-e28d-ab0e-cfb9/forecasts?format=json : EOF","stacktrace":"sbam/pkg/power.(*Power).Handler\n\t/home/runner/work/sbam/sbam/pkg/power/handler.go:30\nsbam/pkg/cmd.schedule\n\t/home/runner/work/sbam/sbam/pkg/cmd/schedule.go:213\nsbam/pkg/cmd.crontabSchedule.func1\n\t/home/runner/work/sbam/sbam/pkg/cmd/schedule.go:244\ngithub.com/robfig/cron/v3.FuncJob.Run\n\t/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136\ngithub.com/robfig/cron/v3.(*Cron).startJob.func1\n\t/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312"}
{"level":"error","ts":"2024-12-18T00:00:01+01:00","msg":"EOF","stacktrace":"sbam/pkg/cmd.schedule\n\t/home/runner/work/sbam/sbam/pkg/cmd/schedule.go:215\nsbam/pkg/cmd.crontabSchedule.func1\n\t/home/runner/work/sbam/sbam/pkg/cmd/schedule.go:244\ngithub.com/robfig/cron/v3.FuncJob.Run\n\t/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136\ngithub.com/robfig/cron/v3.(*Cron).startJob.func1\n\t/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312"}
panic: EOF

goroutine 18 [running]:
sbam/pkg/cmd.schedule({0x4000026067, 0x52}, {0x4000026004, 0x52}, {0x4000022083, 0xb}, 0x40d3880000000000, 0x40b3880000000000, 0x40af3e0000000000, {0x400000e089, ...}, ...)
	/home/runner/work/sbam/sbam/pkg/cmd/schedule.go:216 +0x2a8
sbam/pkg/cmd.crontabSchedule.func1()
	/home/runner/work/sbam/sbam/pkg/cmd/schedule.go:244 +0x50
github.com/robfig/cron/v3.FuncJob.Run(0xf00000000?)
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x24
github.com/robfig/cron/v3.(*Cron).startJob.func1()
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x5c
created by github.com/robfig/cron/v3.(*Cron).startJob in goroutine 7
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0x90
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
{"level":"debug","ts":"2024-12-18T00:00:07+01:00","msg":"Debug Logs activated: true"}
{"level":"info","ts":"2024-12-18T00:00:07+01:00","msg":"Setting Fronius Storage Defaults start..."}
{"level":"debug","ts":"2024-12-18T00:00:07+01:00","msg":"Reading register: 40357 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-18T00:00:07+01:00","msg":"Reading register: 40351 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-18T00:00:07+01:00","msg":"Reading register: 40361 ; value: 1; default:"}
{"level":"debug","ts":"2024-12-18T00:00:07+01:00","msg":"Reading register: 40349 ; value: 0; default:"}
{"level":"debug","ts":"2024-12-18T00:00:07+01:00","msg":"Reading register: 40356 ; value: 10000; default:"}
{"level":"debug","ts":"2024-12-18T00:00:07+01:00","msg":"Writing register: 40349 ; value: 0"}
{"level":"debug","ts":"2024-12-18T00:00:07+01:00","msg":"Writing register: 40356 ; value: 10000"}
{"level":"debug","ts":"2024-12-18T00:00:07+01:00","msg":"Writing register: 40357 ; value: 10000"}
{"level":"debug","ts":"2024-12-18T00:00:07+01:00","msg":"Writing register: 40351 ; value: 0"}
{"level":"debug","ts":"2024-12-18T00:00:07+01:00","msg":"Writing register: 40361 ; value: 1"}
{"level":"info","ts":"2024-12-18T00:00:07+01:00","msg":"Setting Fronius Modbus Defaults done."}
{"level":"debug","ts":"2024-12-18T00:00:07+01:00","msg":"Debug Logs activated: true"}
Running, press ctrl+c to exit...

**Comment by atbore-phx** [comment]
Hi @ougueur,
i'm glad you're using sbam, i'll answer according to the severity:

> {"level":"error","ts":"2024-12-18T00:00:01+01:00","msg":"Error getting forecast for ...

You received this message because there is an issue with Solcast. The error is `EOF` (End of File), probably an empty output. You may have a misconfiguration on the Solcast side. Please check your site configuration on Solcast.
Be careful when sharing your site_id (the number after `rooftop_sites/`); you should keep it private as it's like a password for your metrics. I suggest deleting the site and creating a new one to generate a new code.


> But despite this the battery only charges at about 500/700w and my battery was not full when I woke up at the end of the economic hours ...

Do you have the "Charging from Public Grid" feature enabled on your inverter?  
Check this issue, as it may be the same problem: https://github.com/atbore-phx/sbam/issues/26#issuecomment-2393334343
Check also the prerequites in the doc: https://github.com/atbore-phx/sbam/blob/main/docs/prereq.md

> The economic hours are from 10 p.m. to midnight and midnight to 6 a.m. at my place, should I write 10 p.m. in start hr and 6 a.m. in end hr?

The `start_hr` must be before `end_hr`, so the best configuration would be `start_hr=00:00` and `end_hr=06:00`.

> Can add a parameter for variable rate subscriptions depending on the day, (EDF tempo in France)
Can we make the pw consumption parameter variable depending on the outside temperature (full electric heating by heat pump) my daily consumption depends mainly on the outside temperature.

No, you can't configure it this way at this time. You need to set it manually.

> What is the pw bat reserve parameter used for when the inverter does not know the remaining capacity but only the charge percentage..?

This represents the minimum battery capacity to maintain in any case, in Wh (Default: 4000, which means 4 kWh).
if you don't want a reserve power srt it to zero.
check the add-on doc where all parameter are explained: https://github.com/atbore-phx/sbam/blob/main/home-assistant/addons/sbam/DOCS.md
